In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0-alpha0


In [4]:
#y=a^2*x+b*x+c,分别对a,b,c求导
#求中,x=1,a=2,b=3,c=4
#分别求导的结果应该为da=4,db=1,dc=1
x = tf.constant([1.0])
a = tf.constant([2.0])
b = tf.constant([3.0])
c = tf.constant([4.0])

with tf.GradientTape() as tape:
    tape.watch([a,b,c])
    y = a**2*x+b*x+c

[da,db,dc]=tape.gradient(y,[a,b,c])
print('da:',da)
print('db:',db)
print('dc:',dc)

da: tf.Tensor([4.], shape=(1,), dtype=float32)
db: tf.Tensor([1.], shape=(1,), dtype=float32)
dc: tf.Tensor([1.], shape=(1,), dtype=float32)


In [7]:
x = tf.constant([[1.,3.],[2.5,3]])
a = tf.constant([[10.,2.],[2.,3.]])
with tf.GradientTape() as tape:
    tape.watch([a])
    y = a@x
da = tape.gradient(y,[a])
print(da)

[<tf.Tensor: id=98, shape=(2, 2), dtype=float32, numpy=
array([[4. , 5.5],
       [4. , 5.5]], dtype=float32)>]
