# 1.基本类型

In [7]:
import tensorflow as tf
import numpy as np

In [2]:
tf.constant(1)

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(1.)

<tf.Tensor: id=2, shape=(), dtype=float32, numpy=1.0>

In [4]:
tf.constant(2.2,dtype=tf.double)

<tf.Tensor: id=4, shape=(), dtype=float64, numpy=2.2>

In [5]:
tf.constant([True,False])

<tf.Tensor: id=6, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [6]:
tf.constant('hello world')

<tf.Tensor: id=8, shape=(), dtype=string, numpy=b'hello world'>

# 2.类型转换

In [9]:
a = np.arange(10)
a.dtype

dtype('int32')

In [13]:
a1 = tf.convert_to_tensor(a)#numpy.array转为tf.tensor
a1

<tf.Tensor: id=14, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [14]:
a2 = tf.cast(a1,dtype=tf.float32)
a2

<tf.Tensor: id=16, shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [16]:
a3 = tf.cast(a,dtype=tf.double)
a3

<tf.Tensor: id=19, shape=(10,), dtype=float64, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])>

In [18]:
b = tf.constant([0,1,1,0,1])
b1 = tf.cast(b,dtype=tf.bool)
b1

<tf.Tensor: id=25, shape=(5,), dtype=bool, numpy=array([False,  True,  True, False,  True])>

In [19]:
tf.cast(b1,dtype=tf.int32)

<tf.Tensor: id=27, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 1])>

# 3.tf.Variable()

In [20]:
a = tf.range(10)
a

<tf.Tensor: id=32, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [21]:
#在tensor外再包装一层variable，则变量可实现自动求导功能。
b = tf.Variable(a)
b

<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [22]:
a.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a = tf.ones([])
a

<tf.Tensor: id=46, shape=(), dtype=float32, numpy=1.0>

# 4.tensor常用创建方式

In [28]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: id=51, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [29]:
tf.cast(np.ones([2,3]),dtype=tf.double)

<tf.Tensor: id=53, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [34]:
a= tf.zeros([2,2,2])
a

<tf.Tensor: id=71, shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [35]:
tf.ones(a.shape)

<tf.Tensor: id=75, shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [36]:
tf.fill([2,2],2.2)

<tf.Tensor: id=79, shape=(2, 2), dtype=float32, numpy=
array([[2.2, 2.2],
       [2.2, 2.2]], dtype=float32)>

In [39]:
tf.fill(a.shape,2.3)

<tf.Tensor: id=83, shape=(2, 2, 2), dtype=float32, numpy=
array([[[2.3, 2.3],
        [2.3, 2.3]],

       [[2.3, 2.3],
        [2.3, 2.3]]], dtype=float32)>

# 5.tf.random随机初始化

In [41]:
#正态分布
tf.random.normal([2,3])#均值为0，方差为1

<tf.Tensor: id=97, shape=(2, 3), dtype=float32, numpy=
array([[-1.5848725 , -1.1686643 ,  0.35128686],
       [ 0.0623484 ,  1.1223947 ,  0.622879  ]], dtype=float32)>

In [44]:
tf.random.normal([2,3],mean=10,stddev=4)#均值为2，方差为4

<tf.Tensor: id=118, shape=(2, 3), dtype=float32, numpy=
array([[ 9.248519, 11.916712,  4.832906],
       [11.044123,  9.863404, 11.04403 ]], dtype=float32)>

In [45]:
tf.random.truncated_normal([2,2])#截断的正态分布

<tf.Tensor: id=125, shape=(2, 2), dtype=float32, numpy=
array([[-1.8981291 , -1.2207702 ],
       [ 1.0069933 ,  0.00500305]], dtype=float32)>

In [46]:
#均匀分布
tf.random.uniform([2,3])#0-1的均匀分布

<tf.Tensor: id=133, shape=(2, 3), dtype=float32, numpy=
array([[0.82724714, 0.16230607, 0.992779  ],
       [0.09996474, 0.3285091 , 0.17781866]], dtype=float32)>

In [47]:
tf.random.uniform([2,3],minval=0,maxval=100)#0-100的均匀分布

<tf.Tensor: id=141, shape=(2, 3), dtype=float32, numpy=
array([[96.457245, 75.63483 ,  6.629801],
       [46.80301 , 52.980686, 81.755936]], dtype=float32)>

In [48]:
idx = tf.range(10)
idx

<tf.Tensor: id=146, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [50]:
#随机打散
idx = tf.random.shuffle(idx)
idx

<tf.Tensor: id=149, shape=(10,), dtype=int32, numpy=array([9, 3, 8, 7, 6, 4, 2, 5, 0, 1])>

In [53]:
a = tf.random.uniform([10],maxval=10,dtype=tf.int32)
a

<tf.Tensor: id=162, shape=(10,), dtype=int32, numpy=array([6, 0, 7, 0, 8, 0, 7, 2, 2, 3])>

In [55]:
a = tf.gather(a,idx)
a

<tf.Tensor: id=167, shape=(10,), dtype=int32, numpy=array([0, 2, 6, 0, 7, 7, 2, 8, 3, 0])>

# 6.标量的应用

In [57]:
out = tf.random.uniform([4,10])
out

<tf.Tensor: id=180, shape=(4, 10), dtype=float32, numpy=
array([[0.27102602, 0.15745032, 0.23392117, 0.4087026 , 0.42140853,
        0.6079353 , 0.13728547, 0.85936666, 0.14083278, 0.63008237],
       [0.78649855, 0.9210918 , 0.5469041 , 0.62233114, 0.9635588 ,
        0.29157448, 0.18370199, 0.2638985 , 0.9863163 , 0.65417373],
       [0.00824535, 0.9955671 , 0.05648446, 0.74069524, 0.79868054,
        0.7594416 , 0.22714436, 0.59316456, 0.21360004, 0.3541299 ],
       [0.17268324, 0.6039574 , 0.70408845, 0.7372941 , 0.79675674,
        0.9675634 , 0.5746505 , 0.93159294, 0.5268396 , 0.84868693]],
      dtype=float32)>

In [59]:
y = tf.one_hot(tf.range(4),depth=10)
y

<tf.Tensor: id=193, shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [60]:
loss=tf.keras.losses.mse(y,out)
loss

<tf.Tensor: id=197, shape=(4,), dtype=float32, numpy=array([0.24993172, 0.38288197, 0.42191872, 0.47262573], dtype=float32)>

In [61]:
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: id=200, shape=(), dtype=float32, numpy=0.38183954>

# 7.向量的应用

In [62]:
net = tf.keras.layers.Dense(10)
net.build((4,8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[-0.52799535,  0.27838433, -0.06675744,  0.5083157 ,  0.44180202,
        -0.28941268,  0.17816144,  0.06326771, -0.4242665 , -0.5348991 ],
       [ 0.08283937,  0.5008967 , -0.30919698,  0.45209038,  0.2938859 ,
        -0.39681336, -0.19449925,  0.27999896,  0.2641033 , -0.13312712],
       [-0.45198113,  0.48940396, -0.5280172 ,  0.52846277, -0.14715597,
         0.54721427, -0.1607815 ,  0.3972504 , -0.43171865, -0.55974   ],
       [ 0.40730953,  0.37084866, -0.20025939, -0.50299007,  0.03049523,
        -0.5342019 , -0.46368644, -0.27238825, -0.21366069, -0.13434383],
       [ 0.12717235, -0.06564951,  0.07332325, -0.47195005,  0.05973792,
        -0.26087677,  0.42127943, -0.3497615 , -0.35624802, -0.5553008 ],
       [ 0.21939427,  0.4171604 ,  0.00460702, -0.25214997, -0.37701997,
         0.01867348, -0.16195881,  0.39007908, -0.20885241, -0.3747581 ],
       [-0.1435557 , -0.02383608,  0.50436664, -0.32181752

In [63]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

# 8.矩阵的应用

In [64]:
x = tf.random.normal((4,784))#四张图片，每张打平后为784个数字
x.shape

TensorShape([4, 784])

In [65]:
net = tf.keras.layers.Dense(10)#经过一个10个神经元的网络
net.build((4,784))

In [66]:
net(x).shape

TensorShape([4, 10])

In [67]:
net.kernel.shape

TensorShape([784, 10])

In [68]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>