In [48]:
import tensorflow as tf
import numpy as np

# 1.tf.concat

In [3]:
a = tf.ones([4,35,8])
b = tf.ones([2,35,8])
c = tf.concat([a,b],axis=0)
print(c.shape)

(6, 35, 8)


In [5]:
a = tf.ones([4,32,8])
b = tf.ones([4,3,8])
c = tf.concat([a,b],axis=1)
print(c.shape)

(4, 35, 8)


# 2.tf.stack

In [6]:
a = tf.ones([4,35,8])
b = tf.ones([4,35,8])
tf.stack([a,b],axis=0).shape#同维度可以用stack增加新维度

TensorShape([2, 4, 35, 8])

In [8]:
#拆分
a = tf.ones([2,4,35,8])
print(a.shape)
a1,a2 = tf.unstack(a,axis=0)
print(a1.shape)
print(a2.shape)

(2, 4, 35, 8)
(4, 35, 8)
(4, 35, 8)


# 3.tf.norm

In [9]:
a = tf.ones([2,2])
tf.norm(a)#二范数

<tf.Tensor: id=46, shape=(), dtype=float32, numpy=2.0>

In [10]:
tf.sqrt(tf.reduce_sum(tf.square(a)))#等价于二范数

<tf.Tensor: id=51, shape=(), dtype=float32, numpy=2.0>

In [11]:
tf.norm(a,ord=1)#1范数

<tf.Tensor: id=56, shape=(), dtype=float32, numpy=4.0>

In [16]:
tf.norm(a,ord=2,axis=1)#某个轴上的范数

<tf.Tensor: id=79, shape=(2,), dtype=float32, numpy=array([1.4142135, 1.4142135], dtype=float32)>

# 4.求均值，最大值，最小值

In [17]:
a = tf.random.normal([4,10])
tf.reduce_mean(a)

<tf.Tensor: id=88, shape=(), dtype=float32, numpy=-0.033575498>

In [18]:
tf.reduce_min(a)

<tf.Tensor: id=91, shape=(), dtype=float32, numpy=-2.640803>

In [19]:
tf.reduce_max(a)

<tf.Tensor: id=94, shape=(), dtype=float32, numpy=2.107928>

# 3.最值位置

In [20]:
tf.argmax(a)

<tf.Tensor: id=97, shape=(10,), dtype=int64, numpy=array([1, 2, 1, 3, 2, 2, 2, 1, 1, 3], dtype=int64)>

In [22]:
tf.argmin(a,axis=1)

<tf.Tensor: id=103, shape=(4,), dtype=int64, numpy=array([5, 1, 1, 1], dtype=int64)>

In [23]:
tf.argsort(a)

<tf.Tensor: id=115, shape=(4, 10), dtype=int32, numpy=
array([[5, 8, 1, 9, 3, 7, 0, 2, 6, 4],
       [1, 3, 4, 5, 6, 9, 8, 2, 0, 7],
       [1, 0, 3, 2, 7, 5, 8, 9, 4, 6],
       [1, 8, 2, 6, 4, 7, 0, 5, 3, 9]])>

# 4.tf.equal

In [33]:
a = tf.constant([0,1,2,4,3])
b = tf.range(5)
tf.equal(a,b)

<tf.Tensor: id=148, shape=(5,), dtype=bool, numpy=array([ True,  True,  True, False, False])>

In [34]:
#实例：计算精度accuracy
a = tf.constant([[0.1,0.2,0.7],[0.9,0.05,0.5]])
y = tf.constant([2,1])

In [37]:
pred = tf.cast(tf.argmax(a,axis=1),dtype=tf.int32)
pred

<tf.Tensor: id=159, shape=(2,), dtype=int32, numpy=array([2, 0])>

In [42]:
correct = tf.reduce_sum(tf.cast(tf.equal(pred,y),dtype=tf.int32))
correct/2

<tf.Tensor: id=178, shape=(), dtype=float64, numpy=0.5>

# 5.tf.unique

In [44]:
a = tf.constant([4,3,2,1,2,4,6])
tf.unique(a)

Unique(y=<tf.Tensor: id=186, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 6])>, idx=<tf.Tensor: id=187, shape=(7,), dtype=int32, numpy=array([0, 1, 2, 3, 2, 0, 4])>)

# 6.张量排序

In [45]:
a = tf.random.shuffle(tf.range(10))
a

<tf.Tensor: id=194, shape=(10,), dtype=int32, numpy=array([3, 2, 0, 7, 5, 6, 4, 9, 1, 8])>

In [46]:
tf.sort(a)

<tf.Tensor: id=207, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [47]:
tf.argsort(a)

<tf.Tensor: id=219, shape=(10,), dtype=int32, numpy=array([2, 8, 1, 0, 6, 4, 5, 3, 9, 7])>

In [49]:
a = np.array([[4,3,5],[3,4,5],[3,2,1]])
a

array([[4, 3, 5],
       [3, 4, 5],
       [3, 2, 1]])

In [50]:
#最大的第一个元素
result = tf.math.top_k(a)
result

TopKV2(values=<tf.Tensor: id=223, shape=(3, 1), dtype=int32, numpy=
array([[5],
       [5],
       [3]])>, indices=<tf.Tensor: id=224, shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [0]])>)

In [51]:
#最大钱2个元素
tf.math.top_k(a,2)

TopKV2(values=<tf.Tensor: id=229, shape=(3, 2), dtype=int32, numpy=
array([[5, 4],
       [5, 4],
       [3, 2]])>, indices=<tf.Tensor: id=230, shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [2, 1],
       [0, 1]])>)

# 7.填充

In [52]:
a = tf.reshape(tf.range(9),[3,3])
a

<tf.Tensor: id=238, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [55]:
tf.pad(a,[[1,2],[2,1]])

<tf.Tensor: id=243, shape=(6, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0],
       [0, 0, 3, 4, 5, 0],
       [0, 0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])>

In [56]:
a = tf.random.normal([4,28,28,3])
print(a.shape)
b = tf.pad(a,[[0,0],[2,2],[2,2],[0,0]])
print(b.shape)

(4, 28, 28, 3)
(4, 32, 32, 3)


# 8.复制

In [57]:
a = tf.reshape(tf.range(9),[3,3])
a

<tf.Tensor: id=258, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [58]:
tf.tile(a,[1,2])

<tf.Tensor: id=261, shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

In [59]:
tf.tile(a,[2,1])

<tf.Tensor: id=264, shape=(6, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [62]:
tf.tile(a,[2,2])

<tf.Tensor: id=273, shape=(6, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

# 9.张量限幅

In [63]:
a = tf.range(10)
a

<tf.Tensor: id=278, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [64]:
tf.maximum(a,4)

<tf.Tensor: id=281, shape=(10,), dtype=int32, numpy=array([4, 4, 4, 4, 4, 5, 6, 7, 8, 9])>

In [65]:
tf.minimum(a,4)

<tf.Tensor: id=284, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 4, 4, 4, 4, 4])>

In [66]:
#实例应用：relu函数
a = tf.range(10)-5
a

<tf.Tensor: id=291, shape=(10,), dtype=int32, numpy=array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])>

In [67]:
tf.nn.relu(a)

<tf.Tensor: id=293, shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])>

In [68]:
tf.maximum(a,0)

<tf.Tensor: id=296, shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])>

In [73]:
a = tf.random.normal([2,2],mean=10)
a

<tf.Tensor: id=341, shape=(2, 2), dtype=float32, numpy=
array([[10.085084, 11.994238],
       [ 9.699325,  8.647304]], dtype=float32)>

In [74]:
tf.norm(a)

<tf.Tensor: id=347, shape=(), dtype=float32, numpy=20.357391>

In [75]:
aa=tf.clip_by_norm(a,15)
aa

<tf.Tensor: id=365, shape=(2, 2), dtype=float32, numpy=
array([[7.4310236, 8.837752 ],
       [7.1467834, 6.371619 ]], dtype=float32)>

In [76]:
tf.norm(aa)

<tf.Tensor: id=371, shape=(), dtype=float32, numpy=15.000001>

# 10.张量限幅解决梯度爆炸

In [77]:
import tensorflow as tf
from tensorflow import keras

In [82]:
#载入数据
(x_train,y_train),(x_test,y_test) = keras.datasets.mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(set(y_train))

(60000, 28, 28)
(60000,)
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [89]:
#数据预处理
x = tf.convert_to_tensor(x_train,dtype=tf.float32)/50
y = tf.convert_to_tensor(y_train)
y = tf.one_hot(y_train,depth=10)
print(x.shape,y.shape)

(60000, 28, 28) (60000, 10)


In [90]:
train_db = tf.data.Dataset.from_tensor_slices((x,y)).batch(128).repeat(30)
iteration=iter(train_db)
x,y=next(iteration)
print(x.shape,y.shape)

(128, 28, 28) (128, 10)


In [95]:
#生成初始参数
w1,b1 = tf.Variable(tf.random.truncated_normal([784,512])),tf.Variable(tf.zeros([512]))
w2,b2 = tf.Variable(tf.random.truncated_normal([512,256])),tf.Variable(tf.zeros([256]))
w3,b3 = tf.Variable(tf.random.truncated_normal([256,10])),tf.Variable(tf.zeros([10]))
print(w1.shape,w2.shape,w3.shape)

(784, 512) (512, 256) (256, 10)


In [103]:
#优化器
optimizer = keras.optimizers.SGD(learning_rate=0.01)

In [104]:
#正向传播和反向传播(没有梯度限幅)
def main():

    # 784 => 512
    w1, b1 = tf.Variable(tf.random.truncated_normal([784, 512], stddev=0.1)), tf.Variable(tf.zeros([512]))
    # 512 => 256
    w2, b2 = tf.Variable(tf.random.truncated_normal([512, 256], stddev=0.1)), tf.Variable(tf.zeros([256]))
    # 256 => 10
    w3, b3 = tf.Variable(tf.random.truncated_normal([256, 10], stddev=0.1)), tf.Variable(tf.zeros([10]))

    optimizer = keras.optimizers.SGD(lr=0.01)

    for step, (x,y) in enumerate(train_db):
        # [batch_size, 28, 28]=> [batch_size, 784]
        x = tf.reshape(x, (-1, 784))

        with tf.GradientTape() as tape:
            # layer1
            h1 = x@w1 + b1
            h1 = tf.nn.relu(h1)
            # layer2
            h2=tf.nn.relu(h1@w2 + b2)
            # layer3
            out = tf.nn.relu(h2@w3 + b3)

            #computer loss
            # [batch_size, 10] - [batch_size, 10]
            loss = tf.square(out-y)
            # [batch_size, 10] => [batch_size]
            loss = tf.reduce_sum(loss, axis=1)
            # [batch_size] => scalar
            loss = tf.reduce_mean(loss)

        #compute gradient
        grads = tape.gradient(loss, [w1, b1, w2, b2, w3, b3])
        print('==before global_norm==')
        for g in grads:
            print(tf.norm(g))  #梯度的模，没有考虑方向

        grads, _ =tf.clip_by_global_norm(grads, 15) #梯度的值等比例缩放，都在15以内。

        # print('==after global_norm==')
        # for g in grads:
        #     print(tf.norm(g))  #梯度的模，没有考虑方向

        # update w' = w - lr*grad
        optimizer.apply_gradients(zip(grads, [w1, b1, w2, b2, w3, b3]))
        
        if step % 100 == 0:
            print(step, 'loss: ', float(loss))

main()

==before global_norm==
tf.Tensor(596.0551, shape=(), dtype=float32)
tf.Tensor(17.954102, shape=(), dtype=float32)
tf.Tensor(869.60156, shape=(), dtype=float32)
tf.Tensor(16.078686, shape=(), dtype=float32)
tf.Tensor(1158.7546, shape=(), dtype=float32)
tf.Tensor(20.611927, shape=(), dtype=float32)
0 loss:  168.19178771972656
==before global_norm==
tf.Tensor(199.66295, shape=(), dtype=float32)
tf.Tensor(6.072089, shape=(), dtype=float32)
tf.Tensor(264.3224, shape=(), dtype=float32)
tf.Tensor(5.0609417, shape=(), dtype=float32)
tf.Tensor(350.39838, shape=(), dtype=float32)
tf.Tensor(6.620903, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(34.31205, shape=(), dtype=float32)
tf.Tensor(0.95678604, shape=(), dtype=float32)
tf.Tensor(40.726856, shape=(), dtype=float32)
tf.Tensor(0.7900487, shape=(), dtype=float32)
tf.Tensor(53.277916, shape=(), dtype=float32)
tf.Tensor(1.0675749, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(11.152979, shape=(), dtype=float32)
tf.Tensor(

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.23813409, shape=(), dtype=float32)
tf.Tensor(0.008090111, shape=(), dtype=float32)
tf.Tensor(0.24857692, shape=(), dtype=float32)
tf.Tensor(0.005627466, shape=(), dtype=float32)
tf.Tensor(0.29117295,

tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.86892724, shape=(), dtype=float32)
tf.Tensor(0.034493964, shape=(), dtype=float32)
tf.Tensor(0.87557906, shape=(), dtype=float32)
tf.Tensor(0.025476051, shape=(), dtype=float32)
tf.Tensor(0.9431313, 

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.5815375, shape=(), dtype=float32)
tf.Tensor(0.013045548, shape=(), dtype=float32)
tf.Tensor(0.5479984, shape=(), dtype=float32)
tf.Tensor(0.009133276, shape=(), dtype=float32)
tf.Tensor(0.509361, shape=(), dtype=float32)
tf.Tensor(0.009053707, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dt

==before global_norm==
tf.Tensor(0.090944655, shape=(), dtype=float32)
tf.Tensor(0.0025300665, shape=(), dtype=float32)
tf.Tensor(0.0858875, shape=(), dtype=float32)
tf.Tensor(0.0017675889, shape=(), dtype=float32)
tf.Tensor(0.10229658, shape=(), dtype=float32)
tf.Tensor(0.0019530015, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before gl

==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before gl

==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.25067386, shape=(), dtype=float32)
tf.Tensor(0.009357839, shape=(), dtype=float32)
tf.Tensor(0.26293993, shape=(), dtype=float32)
tf.Tensor(0.0072116163, shape=(), dtype=float32)
tf.Tensor(0.25465375, shape=(), dtype=float32)
tf.Tensor(0.007341854, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dty

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
==before global_norm==
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0

KeyboardInterrupt: 

# 11.tf.where

In [111]:
a = tf.random.normal([3,3])
a

<tf.Tensor: id=2509455, shape=(3, 3), dtype=float32, numpy=
array([[ 2.319352  , -0.78913224, -0.30750674],
       [ 1.2048773 , -0.65423095, -0.23246555],
       [ 1.3241099 , -1.9685179 ,  1.6913482 ]], dtype=float32)>

In [115]:
#取出a中大于0的元素
mask = a>0
tf.boolean_mask(a,mask)

<tf.Tensor: id=2509546, shape=(4,), dtype=float32, numpy=array([2.319352 , 1.2048773, 1.3241099, 1.6913482], dtype=float32)>

In [116]:
#方法2
locations = tf.where(a>0)
tf.gather_nd(a,locations)

<tf.Tensor: id=2509551, shape=(4,), dtype=float32, numpy=array([2.319352 , 1.2048773, 1.3241099, 1.6913482], dtype=float32)>

# 12.tf.scatter_nd

In [118]:
#把数据更新到对应的位置
indices = tf.constant([[2],[6]])
updata = tf.constant([10,15])
shape = tf.constant([8])
tf.scatter_nd(indices,updata,shape)

<tf.Tensor: id=2509561, shape=(8,), dtype=int32, numpy=array([ 0,  0, 10,  0,  0,  0, 15,  0])>

# 13.3D画图

In [127]:
import tensorflow as tf
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [123]:
x = tf.linspace(0.,2.,50)
y = tf.linspace(0.,2.,50)
print(x.shape,y.shape)
print(x,y)

(50,) (50,)
tf.Tensor(
[0.         0.04081633 0.08163265 0.12244898 0.1632653  0.20408162
 0.24489796 0.28571427 0.3265306  0.36734694 0.40816325 0.4489796
 0.48979592 0.53061223 0.57142854 0.6122449  0.6530612  0.6938775
 0.7346939  0.7755102  0.8163265  0.85714287 0.8979592  0.9387755
 0.97959185 1.0204082  1.0612245  1.1020408  1.1428571  1.1836735
 1.2244898  1.2653061  1.3061224  1.3469387  1.387755   1.4285713
 1.4693878  1.5102041  1.5510204  1.5918367  1.632653   1.6734693
 1.7142857  1.755102   1.7959183  1.8367347  1.877551   1.9183673
 1.9591837  2.        ], shape=(50,), dtype=float32) tf.Tensor(
[0.         0.04081633 0.08163265 0.12244898 0.1632653  0.20408162
 0.24489796 0.28571427 0.3265306  0.36734694 0.40816325 0.4489796
 0.48979592 0.53061223 0.57142854 0.6122449  0.6530612  0.6938775
 0.7346939  0.7755102  0.8163265  0.85714287 0.8979592  0.9387755
 0.97959185 1.0204082  1.0612245  1.1020408  1.1428571  1.1836735
 1.2244898  1.2653061  1.3061224  1.3469387  1.387755

In [124]:
x_point,y_point = tf.meshgrid(x,y)
print(x_point.shape)
print(x_point)

(50, 50)
tf.Tensor(
[[0.         0.04081633 0.08163265 ... 1.9183673  1.9591837  2.        ]
 [0.         0.04081633 0.08163265 ... 1.9183673  1.9591837  2.        ]
 [0.         0.04081633 0.08163265 ... 1.9183673  1.9591837  2.        ]
 ...
 [0.         0.04081633 0.08163265 ... 1.9183673  1.9591837  2.        ]
 [0.         0.04081633 0.08163265 ... 1.9183673  1.9591837  2.        ]
 [0.         0.04081633 0.08163265 ... 1.9183673  1.9591837  2.        ]], shape=(50, 50), dtype=float32)


In [126]:
points = tf.stack([x_point,y_point],axis=2)
print(points.shape)
print(points)

(50, 50, 2)
tf.Tensor(
[[[0.         0.        ]
  [0.04081633 0.        ]
  [0.08163265 0.        ]
  ...
  [1.9183673  0.        ]
  [1.9591837  0.        ]
  [2.         0.        ]]

 [[0.         0.04081633]
  [0.04081633 0.04081633]
  [0.08163265 0.04081633]
  ...
  [1.9183673  0.04081633]
  [1.9591837  0.04081633]
  [2.         0.04081633]]

 [[0.         0.08163265]
  [0.04081633 0.08163265]
  [0.08163265 0.08163265]
  ...
  [1.9183673  0.08163265]
  [1.9591837  0.08163265]
  [2.         0.08163265]]

 ...

 [[0.         1.9183673 ]
  [0.04081633 1.9183673 ]
  [0.08163265 1.9183673 ]
  ...
  [1.9183673  1.9183673 ]
  [1.9591837  1.9183673 ]
  [2.         1.9183673 ]]

 [[0.         1.9591837 ]
  [0.04081633 1.9591837 ]
  [0.08163265 1.9591837 ]
  ...
  [1.9183673  1.9591837 ]
  [1.9591837  1.9591837 ]
  [2.         1.9591837 ]]

 [[0.         2.        ]
  [0.04081633 2.        ]
  [0.08163265 2.        ]
  ...
  [1.9183673  2.        ]
  [1.9591837  2.        ]
  [2.         2

In [ ]:
z = x+y