In [1]:
import tensorflow as tf
from tensorflow import keras

# 1.参数会在build以后自动生成

In [2]:
net = keras.layers.Dense(10)

In [3]:
print(net.kernel)
print(net.bias)

AttributeError: 'Dense' object has no attribute 'kernel'

In [4]:
net.build(input_shape=(None,20))
print(net.kernel.shape)
print(net.bias.shape)
print()

(20, 10)
(10,)



In [5]:
out = net(tf.random.normal([10,20]))
print(out.shape)
print(net.kernel.shape)

(10, 10)
(20, 10)


# 2.多层网络使用keras.Sequential堆叠


In [6]:
x = tf.random.normal([4,30])
model = keras.Sequential([
    keras.layers.Dense(20,activation=tf.nn.relu),
    keras.layers.Dense(10,activation=tf.nn.relu),
    keras.layers.Dense(2,activation=tf.nn.relu)
])

model.build(input_shape=[4,30])
model.summary()

for p in model.trainable_variables:
    print(p.name,p.shape)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              multiple                  620       
_________________________________________________________________
dense_2 (Dense)              multiple                  210       
_________________________________________________________________
dense_3 (Dense)              multiple                  22        
Total params: 852
Trainable params: 852
Non-trainable params: 0
_________________________________________________________________
dense_1/kernel:0 (30, 20)
dense_1/bias:0 (20,)
dense_2/kernel:0 (20, 10)
dense_2/bias:0 (10,)
dense_3/kernel:0 (10, 2)
dense_3/bias:0 (2,)


# 2.输出为二分类tf.nn.sigmoid

In [7]:
#sigmoid将输出限制在0-1
a = tf.linspace(-5.,5.,10)
print(tf.reduce_min(a))
print(tf.reduce_max(a))
print(a)
out = tf.nn.sigmoid(a)
print(tf.reduce_min(out))
print(tf.reduce_max(out))
print(out)

tf.Tensor(-5.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(
[-5.         -3.8888888  -2.7777777  -1.6666665  -0.55555534  0.5555558
  1.666667    2.7777781   3.8888893   5.        ], shape=(10,), dtype=float32)
tf.Tensor(0.006692916, shape=(), dtype=float32)
tf.Tensor(0.9933072, shape=(), dtype=float32)
tf.Tensor(
[0.00669292 0.02005756 0.05853692 0.15886912 0.36457652 0.6354236
 0.841131   0.9414632  0.97994244 0.9933072 ], shape=(10,), dtype=float32)


# 3.输出为多分类tf.nn.softmax

In [10]:
a = tf.linspace(-5.,5.,10)
print(tf.reduce_min(a))
print(tf.reduce_max(a))
print(a)
out = tf.nn.softmax(a)#输出映射到0-1
print(tf.reduce_min(out))
print(tf.reduce_max(out))
print(out)

tf.Tensor(-5.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(
[-5.         -3.8888888  -2.7777777  -1.6666665  -0.55555534  0.5555558
  1.666667    2.7777781   3.8888893   5.        ], shape=(10,), dtype=float32)
tf.Tensor(3.0455045e-05, shape=(), dtype=float32)
tf.Tensor(0.67081696, shape=(), dtype=float32)
tf.Tensor(
[3.0455045e-05 9.2514216e-05 2.8103351e-04 8.5370452e-04 2.5933255e-03
 7.8778276e-03 2.3930727e-02 7.2695136e-02 2.2082834e-01 6.7081696e-01], shape=(10,), dtype=float32)


# 4.tf.nn.tanh

In [11]:
a = tf.linspace(-5.,5.,10)
print(tf.reduce_min(a))
print(tf.reduce_max(a))
print(a)
out = tf.nn.tanh(a)#输出映射到-1-1
print(tf.reduce_min(out))
print(tf.reduce_max(out))
print(out)

tf.Tensor(-5.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(
[-5.         -3.8888888  -2.7777777  -1.6666665  -0.55555534  0.5555558
  1.666667    2.7777781   3.8888893   5.        ], shape=(10,), dtype=float32)
tf.Tensor(-0.9999092, shape=(), dtype=float32)
tf.Tensor(0.9999092, shape=(), dtype=float32)
tf.Tensor(
[-0.9999092  -0.9991625  -0.99229795 -0.9311096  -0.50467217  0.5046725
  0.93110967  0.99229795  0.9991625   0.9999092 ], shape=(10,), dtype=float32)
