In [1]:
import tensorflow as tf

# 1.均方误差

In [2]:
y = tf.constant([1,2,5,3,2])
y_onehot = tf.cast(tf.one_hot(y,depth=4),dtype=tf.float32)
out = tf.random.normal([5,4])
loss1= tf.reduce_mean(tf.square(y_onehot-out))
loss2 = tf.square(tf.norm(y_onehot-out))/20
loss3 = tf.reduce_mean(tf.losses.MSE(y_onehot,out))
print(y_onehot)
print(loss1)

tf.Tensor(
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]], shape=(5, 4), dtype=float32)
tf.Tensor(1.4060196, shape=(), dtype=float32)


# 2.三分类问题

In [3]:
x = tf.random.normal([2,4])
w = tf.random.normal([4,3])
b = tf.zeros([3])
y = tf.constant([2,0])

with tf.GradientTape() as tape:
    tape.watch([w,b])
    y_pred = tf.nn.softmax(x@w+b,axis=1)
    loss = tf.reduce_mean(tf.losses.MSE(tf.one_hot(y,depth=3),y_pred))
    
grads = tape.gradient(loss,[w,b])
print(grads[0])
print(grads[1])

tf.Tensor(
[[-0.0008115  -0.01485371  0.01566521]
 [-0.00582381 -0.01852505  0.02434886]
 [-0.16283654  0.0384707   0.12436584]
 [-0.13042755  0.00676373  0.12366383]], shape=(4, 3), dtype=float32)
tf.Tensor([ 0.02572387  0.02123908 -0.04696294], shape=(3,), dtype=float32)


# 3.熵

In [8]:
def entropy(a):
    return -tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.))#将以e为底转换为以2为底

In [10]:
#熵越大，越混乱
a = tf.constant([0.25,0.25,0.25,0.25])
a_entropy = entropy(a)
print(a_entropy)
b = tf.constant([0.1,0.1,0.1,0.7])
b_entropy = entropy(b)
print(b_entropy)
c = tf.constant([0.01,0.01,0.01,0.97])
c_entropy = entropy(c)
print(c_entropy)

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.3567796, shape=(), dtype=float32)
tf.Tensor(0.24194068, shape=(), dtype=float32)


# 4.交叉熵

In [14]:
#衡量两个概率分布的距离,两个概率分布越接近，交叉熵越小
tf.losses.categorical_crossentropy([0,1,0,0],[0.25,0.25,0.25,0.25])

<tf.Tensor: id=284, shape=(), dtype=float32, numpy=1.3862944>

In [15]:
tf.losses.categorical_crossentropy([0,1,0,0],[0.1,0.7,0.1,0.1])

<tf.Tensor: id=303, shape=(), dtype=float32, numpy=0.35667497>

In [16]:
tf.losses.categorical_crossentropy([0,1,0,0],[0.01,0.97,0.01,0.01])

<tf.Tensor: id=322, shape=(), dtype=float32, numpy=0.030459179>

In [18]:
x = tf.random.normal([1,784])
w = tf.random.normal([784,2])
b = tf.zeros(2)
out = x@w+b
pred = tf.nn.softmax(out,axis=1)
print(tf.losses.categorical_crossentropy([0,1],out,from_logits=True))
print(tf.losses.categorical_crossentropy([0,1],pred))

tf.Tensor([2.145765e-06], shape=(1,), dtype=float32)
tf.Tensor([2.1457695e-06], shape=(1,), dtype=float32)
