# 1.单层单输出感知机

In [1]:
import tensorflow as tf
from tensorflow import keras

In [10]:
x = tf.random.normal([1,3])
w = tf.ones([3,1])
b = tf.ones([1])
y = tf.constant([1])

with tf.GradientTape() as tape:
    tape.watch([w,b])
    y_pred = tf.nn.sigmoid(x@w+b)
    loss = tf.losses.binary_crossentropy(y,y_pred)
grads = tape.gradient(loss,[w,b])
print(grads[0])
print(grads[1])

tf.Tensor(
[[ 0.0075632 ]
 [-0.199754  ]
 [ 0.07216299]], shape=(3, 1), dtype=float32)
tf.Tensor([-0.10743831], shape=(1,), dtype=float32)


# 2.单层多输出感知机

In [19]:
x = tf.random.normal([2,3])
w = tf.ones([3,3])
b = tf.ones([3])
y = tf.constant([2,0])
y = tf.one_hot(y,depth=3)
with tf.GradientTape() as tape:
    tape.watch([w,b])
    y_pred = tf.nn.softmax(x@w+b,axis=1)
    loss = tf.losses.categorical_crossentropy(y,y_pred)
grads = tape.gradient(loss,[w,b])
print(grads[0])
print(grads[1])

tf.Tensor(
[[ 0.8828447  -0.9079041   0.0250594 ]
 [ 0.6767018  -0.59937453 -0.07732727]
 [ 0.5486783  -0.3817458  -0.16693251]], shape=(3, 3), dtype=float32)
tf.Tensor([-0.33333334  0.6666667  -0.33333334], shape=(3,), dtype=float32)


# 3.多层感知机

In [20]:
x = tf.constant(1.)
w1 = tf.constant(2.)
b1 = tf.constant(1.)
w2 = tf.constant(3.)
b2 = tf.constant(1.)

with tf.GradientTape(persistent=True) as tape:
    tape.watch([w1, b1, w2, b2])

    y1 = x * w1 + b1
    y2 = y1 * w2 + b2

dy2_dy1 = tape.gradient(y2, [y1])[0]
dy1_dw1 = tape.gradient(y1, [w1])[0]
dy2_dw1 = tape.gradient(y2, [w1])[0]
print(dy2_dy1)
print(dy1_dw1)
print(dy2_dw1)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
